FlightAgencyProject/FlightAgencyProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flights.urls')),
    path('profile/', include('users.urls')),
    path('articles/', include('articles.urls')),
]

FlightAgencyProject/articles/urls.py
from django.urls import path
from .views import *

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view(), name='all_articles'),
    path('<slug:slug>', ArticleDetailView.as_view(), name='article_page'),
]

FlightAgencyProject/flights/urls.py
from django.urls import path
from .views import *
from .api.views import *

app_name = 'flights'
urlpatterns = [
    path('',homepage, name='homepage'),
    path('origin=<str:origin>&destination=<str:destination>', search_flight, name='search_flight'),
    path('flight?<int:pk>', flight_detail_view, name='flight_detail'),
    path('flight-api_GenericAPIView/<int:flight_id>/', ReadUpdateFlightAPI_GenericAPIView.as_view()), #X
    path('create-flight-api_GenericAPIView/', CreateFlightAPI_GenericAPIView.as_view()), #X
    path('readupdatedelete-flight-api/<int:flight_id>/', ReadUpdateDeleteFlightAPI.as_view()),
    path('create-list-flight-api/', CreateListFlightAPI.as_view())
]

FlightAgencyProject/users/urls.py
from django.urls import path
from .views import *
from .api.views import *
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'users'

urlpatterns = [
    path('', profile_view, name='profile'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    # path('profile/<str:username>', profile_view, name='profile'),
    path('Profile/change?password', change_password_view.as_view(), name='change_password'),
    path('profile/Update/<str:pk>', update_profile_view.as_view(), name='edit_info'),
    path('Profile/delete?account?', delete_account_view, name='delete_account'),
    path('login-api/', view=obtain_auth_token),
    path('userinfo-api/', view=UserInfoAPI.as_view()),
    path('user-logout-api/', view=UserLogoutAPI.as_view())
]

FlightAgencyProject/flights/models.py
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return f'{self.name}'


class Airline(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name}'

class Airport(models.Model):
    name = models.CharField(max_length=60)
    symbol = models.CharField(max_length=3)
    city = models.ForeignKey(City, related_name='airports' ,on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.city} ({self.symbol})'


class Flight(models.Model):
    origin = models.ForeignKey(Airport, related_name='flights_from', on_delete=models.CASCADE)
    destination = models.ForeignKey(Airport, related_name='flights_to', on_delete=models.CASCADE)
    airline = models.ForeignKey(Airline, on_delete=models.CASCADE)
    datetime = models.DateTimeField()

    def __str__(self):
        return f'Flight{self.id} {self.origin.city}({self.origin.symbol}) to {self.destination.city}({self.destination.symbol}) via {self.airline}    {self.datetime.strftime("%d/%m/%y  %H:%M")}'

    def str2(self):
        return f'{self.origin.city} ({self.origin.symbol}) to {self.destination.city} ({self.destination.symbol})'


class Passenger(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    national_id = models.CharField(max_length=12, verbose_name='National id', primary_key=True)
    tickets = models.ManyToManyField(Flight)


    def __str__(self):
        return f'{self.first_name} {self.last_name}'

FlightAgencyProject/flights/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class SearchFlight(forms.Form):
    CITIES = City.objects.only('name')
    origin = forms.ModelChoiceField(queryset=CITIES)
    destination = forms.ModelChoiceField(queryset=CITIES)

    def clean_destination(self):
        destination = self.cleaned_data['destination']
        origin = self.cleaned_data['origin']
        if (destination != origin):
            return destination
        else:
            message = 'Origin and Destination cannot be the same'
            self.errors['err'] = message


class AddPassengerForm(ModelForm):
    class Meta:
        model = Passenger
        fields = ['first_name', 'last_name', 'national_id']

    def save(self, commit=True):
        data = super(AddPassengerForm, self).save(commit=commit)
        if Passenger.objects.filter(national_id = self.cleaned_data['national_id']).count() == 0:
            # p = Passenger.objects.create(first_name=self.data['first_name'], last_name=self.data['last_name'],
            #                          national_id=self.data['national_id'])
            p = Passenger.objects.create(first_name=self.cleaned_data['first_name'], last_name=self.cleaned_data['last_name'],
                                     national_id=self.cleaned_data['national_id'])
        else:
            p = Passenger.objects.get(national_id=self.cleaned_data['national_id'])
        p.save()
        return p

FlightAgencyProject/flights/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework.generics import GenericAPIView, ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from .serializers import *
from users.api.permissions import IsAdmin
from flights.models import Flight
from rest_framework.permissions import IsAdminUser

# class SearchFlightAPI(GenericAPIView):
#     permission_classes = (IsAuthenticated, IsAdmin)


class ReadUpdateFlightAPI_GenericAPIView(GenericAPIView):
    permission_classes = [IsAdmin,]
    serializer_class = FlightSerializer
    def get(self, request, flight_id):
        flight = get_object_or_404(Flight, id=flight_id)
        data = self.get_serializer(flight).data  #Also try without ".data"
        return Response(data={'flight': data})

    def put(self, request, flight_id):
        flight = get_object_or_404(Flight, id=flight_id)
        flight_serialized = FlightSerializer(
            instance=flight,
            data= request.data,
            partial=True)
        if flight_serialized.is_valid():
            print("it's valid")
            flight_serialized.save()
            return Response({'message': 'Flight Updated Successfully'})
        return Response({'message': flight_serialized.errors})


class CreateFlightAPI_GenericAPIView(GenericAPIView):
    permission_classes = [IsAdmin,]
    serializer_class = FlightSerializer

    def post(self, request):
        flight_serialized = FlightSerializer(data=request.data)
        if flight_serialized.is_valid():
            flight_serialized.save()
            return Response(data={'message': 'Flight Added Successfully'})
        return Response(data={'message': flight_serialized.errors})


class ReadUpdateDeleteFlightAPI(RetrieveUpdateDestroyAPIView):
    permission_classes = [IsAdminUser,]
    serializer_class = FlightSerializer
    lookup_url_kwarg = 'flight_id'
    queryset = Flight.objects.all()


class CreateListFlightAPI(ListCreateAPIView):
    permission_classes = [IsAdminUser,]
    serializer_class = FlightSerializer
    queryset = Flight.objects.all()

FlightAgencyProject/flights/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import PermissionDenied
from .models import Flight
from .forms import *


def homepage(request):
    if request.method == 'GET':
        form = SearchFlight()
        return render(request, "Homepage.html", context={'flights': Flight.objects.all(),'form': form
                                                         ,'user':request.user
                      })
    elif request.method == 'POST':
        form = SearchFlight(request.POST)
        if form.is_valid():
            origin = form.cleaned_data['origin']
            destination = form.cleaned_data['destination']
            return HttpResponseRedirect(reverse('flights:search_flight', kwargs={'origin':origin, 'destination':destination}))
        return render(request, 'Error_page.html', {'message':form.errors['err']})


def search_flight(request, origin, destination):
    filtered_flights = Flight.objects.filter(origin__city__name=origin, destination__city__name=destination)
    return render(request, 'Search_Flight_Result.html', context={'origin': origin, 'destination': destination, 'filtered_flights': filtered_flights})


# @login_required(login_url='users:login')
# @permission_required('flights.add_passenger', login_url='users:login',)
def flight_detail_view(request, pk):
    flight = Flight.objects.get(pk=pk)
    if request.method == 'GET':
        passengers = flight.passenger_set.all()
        form = AddPassengerForm()
        return render(request, 'Flight_detail_Page.html', context={
            'flight':flight, 'passengers':passengers, 'form':form, 'pk':pk, 'user':request.user})
    elif request.method == 'POST':
        if not request.user.has_perm('flights.add_passenger'):
            raise PermissionDenied()
        form = AddPassengerForm(request.POST)
        if form.is_valid():
            p = form.save(commit=False)
            p.tickets.add(Flight.objects.get(pk=pk))
            p.save()
            form.save_m2m()
            passengers = Flight.objects.get(pk=pk).passenger_set.all()
            return render(request, 'Flight_detail_Page.html', context={
                'flight': flight, 'passengers': passengers, 'form': form, 'pk': pk,
                'message': 'Successfully booked'})
        elif (Passenger.objects.filter(national_id=form.data['national_id']).count() == 1):
            p = Passenger.objects.get(national_id=form.data['national_id'])
            if ((form.data['first_name'] == p.first_name) and (form.data['last_name'] == p.last_name)):
                if p not in Flight.objects.get(pk=pk).passenger_set.all():
                    p.tickets.add(Flight.objects.get(pk=pk))
                    p.save()
                    status = 'Successful'
                    msg = 'Successfully booked'

                else:
                    status = 'Unsuccessful'
                    msg = 'He/She is already booked on the flight'

            elif p not in Flight.objects.get(pk=pk).passenger_set.all():
                msg = 'A person with same national id number is registered on our database, but your enetered name is not corresponding to him/her! please check your entered data or contact us via phone or email'
                status = 'Unsuccessful'
            elif p in Flight.objects.get(pk=pk).passenger_set.all():
                msg = 'A person with same national id number is booked on this flight. However, your enetered name is not corresponding to him/her! Please check your entered data or contact us via phone or email'
                status = 'Unsuccessful'
        else:
            msg = form.errors

        passengers = Flight.objects.get(pk=pk).passenger_set.all()
        return render(request, 'Flight_detail_Page.html', context={
            'flight': flight, 'passengers': passengers, 'form': form, 'pk': pk,
            'message': msg})

FlightAgencyProject/flights/templates/Add_Passenger_Page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

FlightAgencyProject/flights/templates/Error_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Something went wrong!</title>
</head>
<body>
<h1>
{% if message %}
    {{ message }}
    </h1>
{% endif %}
</body>
</html>

FlightAgencyProject/flights/templates/Flight_detail_Page.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ flight.origin }} to {{ flight.destination }} {{ flight.datetime }}</title>
</head>
<body>
{% if user.username %}
    <a href="{% url 'users:profile' %}">User: {{ user.username }}</a>
    <br>
    <a href="{% url 'users:logout' %}">Logout</a>
{% else %}
    <a href="{% url 'users:login' %}">Login</a>
{% endif %}
<h2>Flight ID: {{ pk }}</h2>
<br>
<li>Origin: {{ flight.origin }}</li>
<li>Destination: {{ flight.destination }}</li>
<li>Datetime: {{ flight.datetime|date:'Y/M/j H:i' }}</li>
<li>Airline: {{ flight.airline }}</li>

<br><br>

<h1>Passengers:</h1>
{% for p in passengers %}
    <li>{{ p }}</li>
{% empty %}
    No one on this flight yet!
{% endfor %}

{#{% empty %}#}
{#    <br>#}
{#    No One#}
{#{% endfor %}#}
<br>
<br>
<form action="{% url 'flights:flight_detail' flight.pk%}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit">
</form>

{% if message %}
    {{ message }}
{% endif %}
<br><br>
<a href="{% url 'flights:homepage' %}">Back to Homepage</a>
</body>
</html>

FlightAgencyProject/flights/templates/Homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flights:</title>
</head>
<body>
    {% if not request.user.is_authenticated %}
        <a href="{% url 'users:login' %}">Log in/Sign up</a>
    {% else %}
        <h4>{{ user.username }}</h4>
        <h4>Email: {{ user.email }}</h4>
        <a href="{% url 'users:logout' %}">Log out</a>
        <a href="{% url 'users:profile' %}">Profile Page</a>
    {% endif %}

    <h2>
    <a href="{% url 'articles:all_articles' %}">Articles</a>
    </h2>

    <h1>Hello, These are future flights:</h1>
{% for flight in flights %}
    <a href="{% url 'flights:flight_detail' flight.pk%}">{{ flight.pk }}: {{flight.origin.city}} ({{flight.origin.symbol}}) to {{ flight.destination.city }} ({{ flight.destination.symbol }}) At  "{{ flight.datetime|date:"Y/m/d H:i"}}"<br> </a>
{% endfor %}

<h2>Search</h2>
    <form action="{% url 'flights:homepage' %}" method="post">
        {% csrf_token %}
        <p>{{ form.as_p }}</p>
    <button type="submit">Search</button>
    </form>

</body>
</html>

FlightAgencyProject/flights/templates/Search_Flight_Result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ origin }} to {{ destination }} Flights</title>
</head>
<body>
<h1>Future Flights from {{ origin }} to {{ destination }}</h1>
{% for flight in filtered_flights %}
    <a href="{% url 'flights:flight_detail' flight.pk%}">{{flight.origin.city}} ({{flight.origin.symbol}}) to {{ flight.destination.city }} ({{ flight.destination.symbol }}) At  "{{ flight.datetime|date:"Y/m/d H:i"}}"<br></br> </a>
{% empty %}
    <h3>There is no flight found from {{ origin }} to {{ destination }}</h3>
{% endfor %}
<a href="{% url 'flights:homepage' %}">Back to Homepage</a>
</body>
</html>