FlightAgencyProject/FlightAgencyProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flights.urls')),
    path('profile/', include('users.urls')),
    path('articles/', include('articles.urls')),
]

FlightAgencyProject/users/urls.py
from django.urls import path
from .views import *
from .api.views import *
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'users'

urlpatterns = [
    path('', profile_view, name='profile'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    # path('profile/<str:username>', profile_view, name='profile'),
    path('Profile/change?password', change_password_view.as_view(), name='change_password'),
    path('profile/Update/<str:pk>', update_profile_view.as_view(), name='edit_info'),
    path('Profile/delete?account?', delete_account_view, name='delete_account'),
    path('login-api/', view=obtain_auth_token),
    path('userinfo-api/', view=UserInfoAPI.as_view()),
    path('user-logout-api/', view=UserLogoutAPI.as_view())
]

FlightAgencyProject/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(max_length=150, primary_key=True)
    email = models.EmailField(unique= True)
    country = models.CharField(max_length=20, blank=True, null=True)
    phone = models.CharField(max_length=16, blank=True, null=True)
    class Meta:
        db_table = 'auth_user'

    def __str__(self):
        return self.username

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

FlightAgencyProject/users/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email','username', 'password1', 'password2', 'country', 'phone')

    def save(self, commit=True):
        user = super().save(commit=commit)
        return user


class UpdateProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'country', 'phone')

    # def save(self, commit=True):
    #     user = super().save(commit=commit)
    #     return user


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput())
    new_password = forms.CharField(widget=forms.PasswordInput(),max_length=64)
    new_password_repeated = forms.CharField(widget=forms.PasswordInput(),max_length=64)


class DeleteUserForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput())

FlightAgencyProject/users/api/views.py
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.response import Response


class UserInfoAPI(GenericAPIView):
    permission_classes = (IsAuthenticated,)
    def get(self, request):
        return Response(data={'username': request.user.username,
                              'email': request.user.email,
                              'first name': request.user.first_name,})


class UserLogoutAPI(GenericAPIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        request.user.auth_token.delete()
        return Response(data={'message': f"bye {request.user.first_name}"})

FlightAgencyProject/users/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.urls import reverse ,reverse_lazy
from django.http import Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.views.generic import UpdateView, DetailView, DeleteView
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.views import APIView
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from .models import *
from .forms import *


def login_view(request):
    if request.method =='GET':
        return render(request, 'Login_page.html')
    elif request.method =='POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('flights:homepage'))
        message = 'Invalid Credentials!'
        return render(request, 'Login_page.html', {'message':message})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('flights:homepage'))


def signup_view(request):
    if request.method == 'GET':
        form = SignUpForm()
        return render(request, 'Signup_page.html', {'form':form})
    elif request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            Group.objects.get(name='Registered_users').user_set.add(user)
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return HttpResponseRedirect(reverse('flights:homepage'))
        else:
            return render(request, 'Error_page.html', {'message':form.errors})


def profile_view(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            if request.user.is_superuser:
                return HttpResponse(f' You are a Superuser {request.user.username}')
            # user_profile = get_object_or_404(Profile, username=request.user.username)
            return render (request, 'Profile_page.html', {'user': request.user
                                                              # ,'user_profile': user_profile
                                                              })
        return HttpResponse('You Must Log In First')




class update_profile_view(UpdateView):
    model = User
    fields = ['username', 'email', 'first_name', 'last_name', 'country', 'phone']
    template_name = 'Update_Profile_Page.html'
    success_url = reverse_lazy('flights:homepage')

    def get_object(self, *args, **kwargs):
        obj = super(update_profile_view, self).get_object(*args, **kwargs)
        if obj == self.request.user:
            return obj
        raise Http404


class change_password_view(View):
    def get(self,request):
        form = ChangePasswordForm()
        return render(request, 'Change_Password_Page.html', context={'form':form})
    def post(self,request):
        form = ChangePasswordForm(request.POST)
        if request.user.check_password(form.data['old_password']):
            if form.data['new_password'] == form.data['new_password_repeated']:
                request.user.set_password(form.data['new_password'])
                request.user.save()
                return HttpResponseRedirect(reverse_lazy('users:profile'))
            msg = 'Two passwords which you entered are not identical'
        else:
            msg = 'Your entered password was not correct'
        return HttpResponseRedirect(reverse_lazy('flights:Error_page.html', msg))


def delete_account_view(request):
    # def get(self, request):
    if request.method =='GET':
        form = DeleteUserForm()
        return render(request, 'Delete_User_Page.html', context={'user':request.user,
                                                                 'form':form})
    # def post(self, request):
    elif request.method == 'POST':
        form = DeleteUserForm(request.POST)
        entered_password = form.data['password']
        if request.user.check_password(entered_password):
            username = request.user.username
            user = User.objects.get(username=username)
            user.is_active = False
            logout(request)
            user.delete()
            return HttpResponse('You have been successfully deleted your user account')
        super(delete_account_view)
        return render(request, 'Delete_User_Page.html', context={'user':request.user,
                                                                 'msg':'Wrong Password!'})

FlightAgencyProject/users/templates/Change_Password_Page.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change your Password</title>
</head>
<body>
<form action="{% url 'users:change_password' %}" method="post">
{% csrf_token %}
{{ form|crispy }}
    <input type="submit">
    </form>
</body>
</html>

FlightAgencyProject/users/templates/Delete_User_Page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete user account</title>
</head>
<body>
{% if msg %}
    {{ msg }}
{% endif %}
<form action="{% url 'users:delete_account' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {{ object }}
    <input type="submit">
    </form>
</body>
</html>

FlightAgencyProject/users/templates/Login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log in or Sign Up</title>
</head>
<body>
    {% if message %}
        <h2>{{ message }}</h2>
    {% endif %}
    <h1>Log in:</h1>
    <form action="{% url 'users:login' %}" method='post'>
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" Value="Log in">
    </form>
    <a href="{% url 'users:signup' %}">Sign up</a>
</body>
</html>

FlightAgencyProject/users/templates/Profile_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.firstname }}'s Profile Page</title>
</head>
<body>
    {% if user.is_superuser %}
            You are a Superuser
    {% else %}
    <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
{#    {% if phone %}#}
        <p>Phone Number: {{ user.phone }}</p>
        <p>country: {{ user.country }}</p>
        {% endif %}
{#    {% endif %}#}
    <a href="{% url 'users:change_password' %}">Change Password</a>
    <br>
    <a href="{% url 'users:edit_info' user.username %}">Update your personal information</a>
    <br>
    <a href="{% url 'users:delete_account' %}">Delete Account</a>

    <p></p>


</body>
</html>

FlightAgencyProject/users/templates/Signup_page.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>
<form action="{% url 'users:signup' %}"  method="post">
    {% csrf_token %}
    {{ form|crispy}}
    <input type="submit">
</form>

</body>
</html>

FlightAgencyProject/users/templates/Update_Profile_Page.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit your information</title>
</head>
<body>
<h1>Here you can update your personal information</h1>
<form action = "{% url 'users:edit_info' user.username%}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit">
</form>
</body>
</html>

FlightAgencyProject/users/templates/User_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object.username }}</title>
</head>
<body>
<li>{{ object.username }}</li>
<li>{{ object.first_name }}</li>
<li>{{ object.last_name }}</li>
<li>{{ object.email }}</li>
<li>{{ object.phone }}</li>
</body>
</html>